GigHub/Models/Gig.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace GigHub.Models
{
    public class Gig
    {
        public int Id { get; set; }


        public ApplicationUser Artist { get; set; }

        [Required]
        public string ArtistID { get; set; }

        public DateTime DateTime { get; set; }

        [Required]
        [StringLength(255)]
        public string Venue { get; set; }

        public Genre Genre { get; set; }

        [Required]
        public byte GenreID { get; set; }
    }
}

GigHub/Controllers/GigsController.cs
using GigHub.Models;
using GigHub.ViewModels;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web.Mvc;

namespace GigHub.Controllers
{
    public class GigsController : Controller
    {
        /// <summary>
        ///  Object to access the dbContext to connect the entity framework.
        /// </summary>
        private ApplicationDbContext applicationDbContext;

        /// <summary>
        /// Constructor to create object for DBContext.
        /// </summary>
        public GigsController()
        {
            applicationDbContext = new ApplicationDbContext();
        }

        /// <summary>
        /// Controller to Create or Add the Gigs
        /// Authorize is used to validate only the authorised artist to access this page
        /// </summary>
        /// <returns>ViewModel that contains the list of Gigs</returns>
        [Authorize]
        public ActionResult Create()
        {
            var viewModel = new GigFormViewModel { Genres = applicationDbContext.DbSetGenre.ToList() }; // gigFormViewModel should return Genres
            return View(viewModel);
        }

        /// <summary>
        /// COntroller to Post the created Gigs to Database
        /// </summary>
        /// <param name="gigFormViewModel">ViewModel that contains the Gig Details</param>
        /// <returns>Redirects to the next page</returns>
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken] // Prevents CSRF Forgery attack
        public ActionResult Create(GigFormViewModel gigFormViewModel)
        {
            if (!ModelState.IsValid) // Checks whether the state changes else will go into this method
            {
                gigFormViewModel.Genres = applicationDbContext.DbSetGenre.ToList(); // gigFormViewModel should return Genres
                return View("Create", gigFormViewModel);
            }

            var gig = new Gig
            {
                ArtistID = User.Identity.GetUserId(),
                GenreID = gigFormViewModel.Genre,
                DateTime = gigFormViewModel.GetDateTime(),
                Venue = gigFormViewModel.Venue

            };

            applicationDbContext.DbSetGig.Add(gig); // Add the Gig to the Gig table(dbSetGig) using DB Context(applicationDbContext)
            applicationDbContext.SaveChanges(); // EF will generate the SQL statement and will update the database

            return RedirectToAction("Index", "Home"); // Returns to the Redirect Page. Index - Action, Home - Controller

        }
    }
}

GigHub/Views/Gigs/Create.cshtml
@model GigHub.ViewModels.GigFormViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Add a Gig</h2>
@using (Html.BeginForm("Create", "Gigs"))
{
    <p class="alert alert-warning">All fields are <strong>required</strong></p>
         @Html.AntiForgeryToken()
        <div class="form-group">
            @Html.LabelFor(m => m.Venue)
            @Html.TextBoxFor(m => m.Venue, new { @class = "form-control", autofocus = "autofocus" })
            @Html.ValidationMessageFor(m => m.Venue)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Date)
            @Html.TextBoxFor(m => m.Date, new { @class = "form-control", placeholder = "eg) 1 Jan 2018" })
            @Html.ValidationMessageFor(m => m.Date)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Time)
            @Html.TextBoxFor(m => m.Time, new { @class = "form-control", placeholder = "eg) 20:00" })
            @Html.ValidationMessageFor(m => m.Time)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Genre)
            @Html.DropDownListFor(m => m.Genre, new SelectList(Model.Genres, "Id", "Name"), "", new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Genres)
        </div>
        <button type="submit" class="btn btn-primary">Add a Gig</button>
}
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}